apiVersion: v1
kind: "BuildConfig"
metadata:
    name: "tasks-pipeline"
spec:
    source:
      type: "Git"
      git:
        uri: "REPO"
      contextDir: "openshift-tasks"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
        env:
        - name: "GUID"
          value: "GUIDVALUE" 